### PR TITLE
Get all manage.py commands, get make targets, menus.

### PR DESCRIPTION
**Pull request by vindarel**
Hi there,
I worked to improve the django mode to my taste a few months ago. I think some features can be useful but it isn't really finished and polished yet, and I'd like some help and reviews for that.

What I implemented:
- I wanted completion of available commands
- I wanted to run every possible command available with manage.py (even the ones from plugins like django-extensions)
I did  it by parsing its help output. Now, when one runs `C-c m` (django-manage) he gets the full list of commands, with auto-completion, with a chance to edit it before running it.

- Since I use a Makefile I wanted the same for makefiles, so I do it likewise, by parsing the Makefile at the project root and catching targets with a little regexp. I wonder wether I should put that in a separate project.
- And since Django-mode has a nice menu, and I like it for beginners to have a menu, I tried to add a menu for the django commands and another one for the make commands, but I couldn't do exactly what I want: I only managed to create the menu entries at the left of the menu bar.

With this PR, I'd like to hear you about the new features and I'd love to read your code reviews and discuss wether and how we should/can merge that. Thanks !

### CODE REVIEW

**Comment by myfreeweb** [comment]
Code review? I've completely forgot Emacs Lisp in all these years. What the hell is `progn`? :D And Django. Haven't used Django in, like, 4 years. I'm more of a vim+rails kind of person now.

The only thing I've noticed is that you're making it depend on projectile.

Would you like to get collaborator (push) access? Or... I can just transfer the whole repo to you.

**Comment by vindarel** [comment]
I got it ! You answered yesterday, that must be an april fool !! :)
But it looks like it's not since you're really looking for a maintainer… God damn it, I have no chance with asking code reviews. 
Look, I can't have push access now because my patch isn't satisfying (and I don't think I have the shoulders in elisp anyway). Maybe when I make it right ?
Did you ask other collaborators (@yasuyk for instance) ?

**Comment by myfreeweb** [comment]
I don't do april fools really.

Feel free to find someone with good elisp skills :) I just don't care about this project anymore.

**Comment by vindarel** [comment]
Closing in favor of smaller and cleaner PRs, like https://github.com/myfreeweb/django-mode/pull/20

**Pull request closed without merging**
